//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using Assistant;
using UnityEngine;

namespace ClassicUO.Game.UI.Assistant
{
    internal class Resources
    {
        private const string AssistantResourcesPath = "Assistant/";
        internal static string defaultConfig => GetResource("Config");
        internal static string defaultProfile => GetResource("Profile");
        internal static string defaultSkills => GetResource("skills");
        internal static string defaultSpells => GetResource("spells");
        internal static string defaultBodies => GetResource("bodies");
        internal static string defaultBuffIcons => GetResource("bufficons");
        internal static string defaultFoods => GetResource("foods");

        private static string GetResource(string resourceName)
        {
            var path = AssistantResourcesPath + resourceName;
            var resource = UnityEngine.Resources.Load<TextAsset>(path);
            if (resource == null)
            {
                Debug.LogError($"Resource not found at {path}");
                return null;
            }
            return resource.text;
        }
    }
}
